### ISSUE TITLE
Unknown package com.textile.dev in Android Studio

### ISSUE THREAD

**Issue by undercase** [textileio/photos#1162]
Since the latest updates, I'm unable to test the application in android studio. It is failing to install the APK on my virtual device because of the error `Unkown package: com.textile.dev`.

```06/12 01:02:10: Launching app
$ adb install-multiple -r -t C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\slices\slice_5.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\slices\slice_8.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\slices\slice_2.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\resources\instant-run\debug\resources-arm64-v8a-debug.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\slices\slice_0.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\slices\slice_4.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\dep\dependencies.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\slices\slice_6.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\resources\instant-run\debug\resources-armeabi-v7a-debug.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\slices\slice_9.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\slices\slice_7.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\slices\slice_3.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\split-apk\debug\slices\slice_1.apk C:\Users\hoboh\Documents\Textile\photos\android\app\build\intermediates\instant-run-apk\debug\app-arm64-v8a-debug.apk 
$ adb shell pm uninstall com.textile.dev
Unknown failure: Exception occurred while executing:
java.lang.IllegalArgumentException: Unknown package: com.textile.dev
at com.android.server.pm.Settings.isOrphaned(Settings.java:4289)
at com.android.server.pm.PackageManagerService.isOrphaned(PackageManagerService.java:21095)
at com.android.server.pm.PackageManagerService.deletePackageVersioned(PackageManagerService.java:17916)
at com.android.server.pm.PackageInstallerService.uninstall(PackageInstallerService.java:736)
at com.android.server.pm.PackageManagerShellCommand.runUninstall(PackageManagerShellCommand.java:1486)
at com.android.server.pm.PackageManagerShellCommand.onCommand(PackageManagerShellCommand.java:193)
at android.os.ShellCommand.exec(ShellCommand.java:103)
at com.android.server.pm.PackageManagerService.onShellCommand(PackageManagerService.java:21330)
at android.os.Binder.shellCommand(Binder.java:634)
at android.os.Binder.onTransact(Binder.java:532)
at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:2821)
at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3856)
at android.os.Binder.execTransact(Binder.java:731)
Error while Installing APKs
```

**Comment by undercase** [comment]
Fixed this by setting `def enableSeparateBuildPerCPUArchitecture = true` to false in `android/app/build.gradle`.
